name: tasareeh
description: A new Flutter project.
version: 1.0.0+4

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  http: ^1.1.0
  fluid_bottom_nav_bar: ^1.4.0
  otp_text_field: ^1.1.3
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  syncfusion_flutter_signaturepad: ^23.1.39
  animated_splash_screen: ^1.3.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  open_file: ^3.3.2
  dio: ^5.3.3
  lottie: ^2.6.0
  flutter_spinkit: ^5.2.0
  webview_flutter: ^4.4.1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.1.14
  flutter_file_downloader: ^1.1.0+1

  #
  # firebase_core: ^2.3.0
  # cloud_firestore: ^4.1.0
  # firebase_auth: ^4.1.4
  # provider: ^6.0.5
  # flutter_inappwebview: ^5.7.2+3
  # flutter_downloader: ^1.11.3
  # cupertino_icons: ^1.0.2
  # url_strategy: ^0.2.0
  # get: ^4.6.5
  # printing: ^5.9.3
  # pdf: ^3.8.4
  # syncfusion_flutter_pdf: ^23.1.38
  # font_awesome_flutter: ^10.5.0
  # flutter_custom_clippers:
  # flutter_launcher_icons: ^0.13.1
  # flutter_signature_pad: ^3.0.1
  # blurry_modal_progress_hud: ^1.1.1
  # flutter_file_downloader: ^1.1.0+1
  # url_launcher: ^6.1.14
  # flutter_cached_pdfview: ^0.4.2
  # page_transition: ^2.1.0
  # flutter_pdfview: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "asset/logo.png"

  android: true
  ios: true
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png
    - assets/out.png
    - assets/ok.json
    - assets/up.json
    - assets/upl.json
    - assets/loading.json